openapi: 3.0.0
x-stoplight:
  id: 8tlfrgw6uetjc
info:
  title: TEST API
  version: "1.0"
  description: TESTのAPI仕様書
  contact:
    name: nothing
servers:
  - url: "http://localhost:3000"
paths:
  "/users/{userid}":
    get:
      summary: ユーザー情報取得
      tags:
        - users
      responses:
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/user"

        "204":
          description: No Content
        "400":
          description: Bad Request
      operationId: "get-users-[userid]"
      description: ユーザー情報取得
      parameters: []
      x-internal: false
    put:
      summary: ユーザー情報編集
      operationId: "put-users-[userid]"
      description: ユーザー情報編集
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: uuid
                  example: xxxx-xxx-xxxx
      tags:
        - users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

        "400":
          $ref: "#/components/responses/400"
        "404":
          description: Not Found
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true

  /users:
    post:
      summary: ユーザー情報登録
      operationId: post-users
      responses:
        "201":
          description: Created
        "400":
          $ref: "#/components/responses/400"
      tags:
        - users
      description: ユーザー情報登録
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
            examples: {}
        description: ""

components:
  schemas:
    user:
      title: user
      x-stoplight:
        id: z6f6l8b36wynu
      type: object
      properties:
        id:
          type: string
          description: uuid
        name:
          type: string
        image:
          type: string
        email:
          type: string
        service_line:
          type: string
        isAdmin:
          type: boolean
  responses:
    "400":
      description: 失敗
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: "400 bad Request"
                example: "400 bad Request"

    "401":
      description: 権限エラー
security: []
tags:
  - name: users
